Simplify

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -33,47 +33,19 @@ jobs:
       - name: Install lcov
         run: sudo apt-get update > /dev/null && sudo apt-get install lcov > /dev/null
 
-      - name: Run tests with coverage for controller
-        run: flutter test --coverage test/controller || true
-
-      - name: Calculate code coverage percentage for controller
-        run: |
-          lcov --summary coverage/lcov.info | grep lines | awk '{print $2}'
-        id: coverage_controller
-      
-      # - name: Publish coverage report for controller
-      #   uses: actions/upload-artifact@v3
-      #   with:
-      #     name: coverage-report-controller
-      #     path: coverage/lcov-report
-
-      - name: Run tests with coverage for models
-        run: flutter test --coverage test/models || true
-
-      - name: Calculate code coverage percentage for models
-        run: |
-          lcov --summary coverage/lcov.info | grep lines | awk '{print $2}'
-        id: coverage_models
-
-      # - name: Publish coverage report for models
-      #   uses: actions/upload-artifact@v3
-      #   with:
-      #     name: coverage-report-models
-      #     path: coverage/lcov-report
+      - name: Run tests with coverage
+        run: flutter test --coverage test/controller test/models || true
 
       - name: Check coverage threshold and set job status
         run: |
-          coverage_percentage_controller="${{ steps.coverage_controller.outputs.stdout }}"
-          coverage_percentage_models="${{ steps.coverage_models.outputs.stdout }}"
-          coverage_value_controller=$(echo "$coverage_percentage_controller" | sed 's/%//')
-          coverage_value_models=$(echo "$coverage_percentage_models" | sed 's/%//')
+          coverage=$(lcov --summary coverage/lcov.info | grep lines | awk '{print $2}')
 
           threshold=80.0
-
-          if (( $(echo "$coverage_value_controller >= $threshold" | bc -l) )) && (( $(echo "$coverage_value_models >= $threshold" | bc -l) )); then
-            echo "Code coverage is above threshold. CI/CD passes."
-            exit 0
+          
+          if [[ "$(awk -v a=$coverage -v b=$threshold 'BEGIN { print (a >= b) }')" == "1" ]]; then
+              echo "Code coverage is above threshold. CI/CD passes."
+              exit 0
           else
-            echo "Code coverage is below threshold. CI/CD fails. Coverage for controller: $coverage_percentage_controller%, Coverage for models: $coverage_percentage_models%"
-            exit 1
+              echo "Code coverage is below threshold. CI/CD fails. Coverage: $coverage"
+              exit 1
           fi
